# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: ContosoDevExp
metadata:
  name: Contoso
  description: A development box for building and testing Azure Dev CLI
  version: 0.1.0
infra:
  provider: bicep
  path: ./infra/main.bicep
pipeline:
  provider: github
workflows:
  up: 
    steps:
      - name: Create a new Azure Dev CLI environment
        run: az dev env create -n ${{ inputs.name }} -l ${{ inputs.location }}
        inputs:
          name:
            description: The name of the environment
            type: string
            default: dev
          location:
            description: The location of the environment
            type: string
            default: eastus2
      - name: up
        run: azd up -e -n ${{ inputs.name }}
        inputs:
          name:
            description: The name of the environment
            type: string
            default: dev
